version: "3.9"
services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: docgenie
      POSTGRES_PASSWORD: docgenie
      POSTGRES_DB: docgenie
    volumes: [db_data:/var/lib/postgresql/data]
    ports: ["5432:5432"]

  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]

  backend:
    build: ./backend
    env_file: backend/.env
    command: >
      sh -c "alembic upgrade head &&
             uvicorn app.main:app --host 0.0.0.0 --port 8000"
    volumes: ["./backend:/code"]
    depends_on: [db, redis]

  worker:
    build: ./backend
    env_file: backend/.env
    command: celery -A app.core.celery_app.celery_app worker -l INFO -Q default -c 4
    depends_on: [db, redis]

volumes:
  db_data:
